# Generated by Django 2.2.5 on 2021-05-30 06:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outbound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('order_quantity', models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('platform', models.CharField(choices=[('Shopee', 'Shopee'), ('Lazada', 'Lazada'), ('Other', 'Other')], max_length=200, null=True)),
                ('remarks', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Out of Delivery', 'Out of Delivery'), ('Completed', 'Completed'), ('Rejected', 'Rejected')], default='Pending', max_length=200)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Product')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Seller', to_field='user_id')),
            ],
        ),
    ]
